// firebase.js - generated by ChatGPT
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js";
import { getFirestore } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyAnWMWR-eN_2YhooCw5-FXU4GT9cokaOJc",
  authDomain: "banco-de-dados-lucao.firebaseapp.com",
  projectId: "banco-de-dados-lucao",
  storageBucket: "banco-de-dados-lucao.firebasestorage.app",
  messagingSenderId: "953706728099",
  appId: "1:953706728099:web:6ef8fe2c3ff04cb0e00d16",
  measurementId: "G-SFG0PPMVWM"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

export { db };
